using InternalRequestsManagement.EntityFrameworkCore;

namespace InternalRequestsManagement;

public class InternalRequestsManagementWebCollection : InternalRequestsManagementEntityFrameworkCoreCollectionFixtureBase
{

}
