using InternalRequestsManagement.EntityFrameworkCore;
using Xunit;

namespace InternalRequestsManagement.EntityFrameworkCore;

public class InternalRequestsManagementEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<InternalRequestsManagementEntityFrameworkCoreFixture>
{

}
