using Xunit;

namespace InternalRequestsManagement.EntityFrameworkCore;

[CollectionDefinition(InternalRequestsManagementTestConsts.CollectionDefinitionName)]
public class InternalRequestsManagementEntityFrameworkCoreCollection : ICollectionFixture<InternalRequestsManagementEntityFrameworkCoreFixture>
{

}
