using Volo.Abp;

namespace InternalRequestsManagement.EntityFrameworkCore;

public abstract class InternalRequestsManagementEntityFrameworkCoreTestBase : InternalRequestsManagementTestBase<InternalRequestsManagementEntityFrameworkCoreTestModule>
{

}
